### ISSUE TITLE
Need a non all to all push_parallel_vector_data 

### ISSUE THREAD

**Issue by loganharbour** [libMesh/TIMPI#18]
Need to implement a `push_parallel_vector_data()` that doesn't use `alltoall()`, similar to how it is done in `push_parallel_packed_range()`.

**Comment by loganharbour** [comment]
@fdkong

**Comment by fdkong** [comment]
We misunderstood. I think @roystgnr already implemented this. We do not need to do anything.

**Comment by roystgnr** [comment]
No, wait - look at the vector<vector> overload.  The vector<T> overload for fixed-size T uses NBX rather than alltoall, but the vector<vector> overload is still less efficient than it should be.

And, that said... I'm not sure why.  I wonder if maybe I started breaking that out into a separate overload when I was afraid that I wasn't going to be able to do a properly probeable asynchronous send(vector<vector>), and then I didn't go back to the same codepath afterwards?  Anyway, there's still a performance problem here, even if it doesn't affect every case.  And I don't think it'll be too hard to fix.

**Comment by fdkong** [comment]
> No, wait - look at the `vector<vector>` overload. The `vector<T>` overload for fixed-size T uses NBX rather than alltoall, but the `vector<vector>` overload is still less efficient than it should be.

I currently only use the case: the `vector<T>` overload for fixed-size T. I am fine for at this moment.

`Equation system init`  involving creating matrix sparsity is not quite scalable right now. It is using the `vector<vector>` version?

**Comment by roystgnr** [comment]
We're using the more-poorly-scaling ```vector<vector>``` version in DofMap::allgather_recursive_constraints, DofMap::scatter_constraints, and DofMap::gather_constraints, none of which are involved in creating matrix sparsity, but each of which does get called right before matrix sparsity patterns are created.

It looks like we might be able to get this working with NBX by just adding a couple new possibly_receive() overloads?  I'll give that a try.

**Comment by roystgnr** [comment]
The good news is that I have this compiling now.  The bad news is that it's failing libMesh unit tests and that bugs in asynchronous MPI code are *especially* hard to debug.  IMHO this validates the whole parallel_sync.h philosophy, though; it'll be great to debug this just once and then have it working in three places.

**Comment by roystgnr** [comment]
Four places.  I didn't notice at first glance, but it's also in DofMap::set_nonlocal_dof_objects.

**Comment by roystgnr** [comment]
I think I may have this working now.  Not confident though; my last commit message was ```Fixup the possibly_receive(vec<vec>) fixup fixup```.  It'll take a while to clean up the history and get the PR going...
