### ISSUE TITLE
undefined sum(T&) with T=double

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/TIMPI#74]
I found a strange problem which I don't fully understand yet: In my user-code I use the `sum()` function with `Real` variable (I configured `Number` as complex).
When compiling, I see the warning
````
/data/..../include/timpi/communicator.h:431:8: warning: inline function ‘void TIMPI::Communicator::sum(T&) const [with T = double]’ used but never defined
````
which agrees to my mind with the specializations in `timpi/parallel_communicator_specializations`.
Interestingly, this leads to an error `undefined reference to `void TIMPI::Communicator::sum<double>(double&) const'` in `opt`-mode only, while it compiles without further trouble in debug-mode.

I am irritated by this behavior, but before I spend much time understanding this in more detail, probably you can tell easily what is going on? Should the specialization be somewhere else or is it actually missing?
If not, I'll look into it and hopefully than I can give more detail than.

With best regards

**Comment by roystgnr** [comment]
The specialization chosen should be in timpi/parallel_implementation.h, around line 2525.  Is it possible that that header is getting indirectly included for you but only ifdef NDEBUG for some reason?

**Comment by BalticPinguin** [comment]
Hi John,
thank you for the reply.
Indeed, including `timpi/parallel_implementation.h` solves the problem.
I found it particularly strange that in one case it is a warning and in the other leads to fatal error.
but having it fixed is the more important end :-)

Many thanks 
Hubert

**Comment by roystgnr** [comment]
It's Roy this time!  Just because John's *usually* the helpful one doesn't mean John's *always* the helpful one!

My guess is that the compiler's able to handle an undefined inline function if at link time it finds a non-inline implementation to link to, so they only make that a warning because it's only a performance issue and a "code smell" rather than an unrecoverable error; but if it makes it to link time and *still* can't find a definition then there's nothing left to do but scream and die.  And my even shakier guess is that, without optimizations cranked up, the compiler generates non-inlined binary code for many functions that it might otherwise inline (and so the linker can use one of those from a different object file; sum(double) is everywhere), but in opt mode that function literally always gets inlined so the linker has nothing to reach for?  But I'm still surprised devel failed too (we do use -O2 there, IIRC, we just turn on -DNDEBUG too), so maybe I don't know what I'm talking about here.  Glad it got fixed regardless.

**Comment by BalticPinguin** [comment]
> It's Roy this time! Just because John's usually the helpful one doesn't mean John's always the helpful one!

oh, sorry. The name looks not even similar :-) So thank you ROY for that help!
the `devel`-mode actually leads to a working executable. Maybe somewhere is a "hidden" include that I missed...
